# publish the content of the websites
name: publish_websites

on:
  push:
    branches:
      - main

jobs:
  publish_website:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: publish
        env:
          MARKDOWN_NINJA_API_KEY: ${{ secrets.MARKDOWN_NINJA_API_KEY }}
        working-directory: website
        run: |
          docker run -i --rm -e MARKDOWN_NINJA_API_KEY -v `pwd`:/mdninja ghcr.io/bloom42/markdown-ninja publish

  publish_docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: publish
        env:
          MARKDOWN_NINJA_API_KEY: ${{ secrets.MARKDOWN_NINJA_API_KEY }}
        working-directory: docs
        run: |
          docker run -i --rm -e MARKDOWN_NINJA_API_KEY -v `pwd`:/mdninja ghcr.io/bloom42/markdown-ninja publish
